"""Generate a synthetic warm eddy sea-surface temperature anomaly field.

The output is intentionally synthetic demo data. It is safe to commit to a
public repository and does not contain private observations or research data.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import random
from pathlib import Path


DEFAULT_OUTPUT_DIR = Path("data")
DEFAULT_CSV_NAME = "synthetic_warm_eddy_sst_anomaly.csv"
DEFAULT_METADATA_NAME = "synthetic_warm_eddy_metadata.json"


def linspace(start: float, stop: float, count: int) -> list[float]:
    if count < 2:
        return [start]
    step = (stop - start) / (count - 1)
    return [start + index * step for index in range(count)]


def build_field(grid_size: int, seed: int) -> tuple[list[float], list[float], list[list[float]], dict[str, float]]:
    rng = random.Random(seed)
    lons = linspace(150.0, 160.0, grid_size)
    lats = linspace(68.0, 74.0, grid_size)

    center_lon = 155.2
    center_lat = 71.1
    amplitude_c = 2.4
    sigma_lon = 1.05
    sigma_lat = 0.72

    values: list[list[float]] = []
    for lat in lats:
        row: list[float] = []
        for lon in lons:
            lon_term = ((lon - center_lon) / sigma_lon) ** 2
            lat_term = ((lat - center_lat) / sigma_lat) ** 2
            eddy = amplitude_c * math.exp(-0.5 * (lon_term + lat_term))

            background = 0.015 * (lon - 155.0) - 0.025 * (lat - 71.0)
            wave = 0.16 * math.sin((lon - 150.0) * math.pi / 2.8) * math.cos((lat - 68.0) * math.pi / 2.2)
            noise = rng.uniform(-0.035, 0.035)
            row.append(round(eddy + background + wave + noise, 4))
        values.append(row)

    truth = {
        "center_lon": center_lon,
        "center_lat": center_lat,
        "amplitude_c": amplitude_c,
        "sigma_lon_degrees": sigma_lon,
        "sigma_lat_degrees": sigma_lat,
    }
    return lons, lats, values, truth


def write_matrix_csv(path: Path, lons: list[float], lats: list[float], values: list[list[float]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["lat_lon"] + [f"{lon:.4f}" for lon in lons])
        for lat, row in zip(lats, values):
            writer.writerow([f"{lat:.4f}"] + [f"{value:.4f}" for value in row])


def write_metadata(path: Path, grid_size: int, seed: int, truth: dict[str, float]) -> None:
    metadata = {
        "dataset": "synthetic demo data",
        "variable": "sea_surface_temperature_anomaly",
        "units": "degree_C",
        "grid_size": grid_size,
        "random_seed": seed,
        "truth": truth,
        "note": "Generated by generate_sample.py. No private or observational data is included.",
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate synthetic warm eddy demo data.")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--grid-size", type=int, default=96)
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.grid_size < 12:
        raise SystemExit("--grid-size must be at least 12")

    lons, lats, values, truth = build_field(args.grid_size, args.seed)
    csv_path = args.output_dir / DEFAULT_CSV_NAME
    metadata_path = args.output_dir / DEFAULT_METADATA_NAME

    write_matrix_csv(csv_path, lons, lats, values)
    write_metadata(metadata_path, args.grid_size, args.seed, truth)

    print(f"Wrote synthetic demo data: {csv_path}")
    print(f"Wrote metadata: {metadata_path}")


if __name__ == "__main__":
    main()

